### PR TITLE
Add sealed boxes

### PR DESCRIPTION
**Pull request by adbario**
Add libsodium methods to manage [sealed boxes](https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html)

- crypto_box_seal
- crypto_box_seal_open

### CODE REVIEW

**Comment by mattsmithies** [comment]
Great work, I'm going to be adding an alternative ES6 await/async approach which removes the callbacks, but apart from that I can't see any issues. 

I assume the sealed box methods were copy and pasted from another source?

**Comment by adbario** [comment]
I used other methods from the same package as a source, copied and modified them for sealed boxes. Also added the constant crypto_box_sealbytes that comes from libsodium and is needed for crypto_box_seal methods.

**Comment by mattsmithies** [comment]
For now I'd like to add the below ES6 await/aync example code to the README instructions as an perferred alternative to the callback version.

```
const sodiumBoxSealExample = async (plaintext: string) => {

   const keys = await Sodium.crypto_box_keypair();
   const { pk, sk } = keys;

   console.log(`Public key: ${pk}`);
   console.log(`Private key: ${sk}`);

   // Base64 encode message
   const encoded = Buffer.from(plaintext, "utf8").toString("base64");

   // Encrypt
   const encrypted = await Sodium.crypto_box_seal(encoded, pk);

   // Decrypt
   const decrypted = await Sodium.crypto_box_seal_open(encrypted, pk, sk);

   // Base64 decode
   const decoded = Buffer.from(decrypted, "base64").toString("utf8");

   console.log(`Decrypted and decoded: ${decoded}`);
   console.log(`Success? ${plaintext === decoded}`);
 }
``` 

Also when we fully add this functionality to our react native apps we'll need to add it into a separate [Sega](https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html) (see [SW RN Generator](https://github.com/simpleweb/generator-react-native)) which is fired through the use of Actions. 

Don't worry too much about this at the moment, but if you wanted get your head around the concepts explore the Wallet generation for [Miles](https://github.com/simpleweb/miles).

More specifically these links will help you follow the flow for how actions and segas fit together:
- Wallet Generate [Sega](https://github.com/simpleweb/Miles/blob/master/App/Sagas/Wallet.js) 
- Wallet [Helper](https://github.com/simpleweb/Miles/blob/master/App/Helpers/Wallet.js)
- Wallet [Action](https://github.com/simpleweb/Miles/blob/master/App/Actions/Wallet.js) 
- Container [Generate function](https://github.com/simpleweb/Miles/blob/master/App/Scenes/GenerateWallet/Container.js)
- Index (line 64) [Generate Usage](https://github.com/simpleweb/Miles/blob/master/App/Scenes/GenerateWallet/index.js)

**Review by mattsmithies — CHANGES_REQUESTED** [review]
Please update the README to include the ES6 approach for usage. Also all quoted strings in the README need to change to double quotes.

**Review by mattsmithies — APPROVED** [review]

**Comment by mattsmithies** [comment]
🚀

**Pull request merged**
